# Generated by Django 6.1.1 on 2026-09-15 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arbitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='CategoriePoids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('poids_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('poids_max', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'Catégories de poids',
                'ordering': ['poids_min'],
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('ville', models.CharField(max_length=100)),
                ('date_fondation', models.DateField()),
                ('nombre_combattants', models.PositiveIntegerField(default=0)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clubs/')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Boxeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('nationalite', models.CharField(max_length=100)),
                ('taille_cm', models.PositiveIntegerField()),
                ('envergure_cm', models.PositiveIntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='boxeurs/')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('retraite', 'Retraité'), ('suspendu', 'Suspendu')], default='actif', max_length=20)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boxeurs', to='gala.categoriepoids')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boxeurs', to='gala.club')),
            ],
            options={
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Gala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('lieu', models.CharField(max_length=150)),
                ('ville', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('affiche', models.ImageField(blank=True, null=True, upload_to='galas/')),
                ('statut', models.CharField(choices=[('a_venir', 'À venir'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='a_venir', max_length=20)),
                ('capacite_max', models.PositiveIntegerField()),
                ('organisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='galas_organises', to='gala.club')),
            ],
            options={
                'ordering': ['date', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Combat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_combat', models.CharField(choices=[('preliminaire', 'Préliminaire'), ('co_main', 'Co-main event'), ('main_event', 'Main event')], default='preliminaire', max_length=20)),
                ('nb_rounds', models.PositiveIntegerField()),
                ('resultat', models.CharField(choices=[('non_joue', 'Pas encore joué'), ('victoire_rouge', 'Victoire coin rouge'), ('victoire_bleu', 'Victoire coin bleu'), ('nul', 'Match nul')], default='non_joue', max_length=20)),
                ('methode', models.CharField(blank=True, choices=[('ko', 'KO'), ('tko', "TKO / Arrêt de l'arbitre"), ('decision', 'Décision'), ('abandon', 'Abandon'), ('disqualification', 'Disqualification')], max_length=20, null=True)),
                ('ordre', models.PositiveIntegerField(default=1)),
                ('arbitre_assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combats_assistant', to='gala.arbitre')),
                ('arbitre_principal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combats_principal', to='gala.arbitre')),
                ('boxeur_bleu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='combats_bleu', to='gala.boxeur')),
                ('boxeur_rouge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='combats_rouge', to='gala.boxeur')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gala.categoriepoids')),
                ('gala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combats', to='gala.gala')),
            ],
            options={
                'ordering': ['gala', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='Billet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_place', models.CharField(choices=[('gradin', 'Gradin'), ('ringside', 'Ringside'), ('vip', 'VIP')], max_length=20)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date_achat', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billets', to=settings.AUTH_USER_MODEL)),
                ('gala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billets', to='gala.gala')),
            ],
            options={
                'ordering': ['-date_achat'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueSuppression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_combat', models.CharField(max_length=255)),
                ('raison', models.TextField()),
                ('date_suppression', models.DateTimeField(auto_now_add=True)),
                ('supprime_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Historiques de suppression',
                'ordering': ['-date_suppression'],
            },
        ),
    ]
